### ISSUE TITLE
Implement Statistics Functions

### ISSUE THREAD

**Issue by roshanr10** [team4909/2018-Core#27]
Waiting for #26.

Once the match data is decided, I would like the following functions to be implemented:

- `tga.getAverage(team_number, statistic, callback)`
- `tga.getMaximum(team_number, statistic, callback)`

**Comment by nickdelta52** [comment]
Team 811 can assist with this, we have js experience but may need some direction on how this should be implemented.

**Comment by roshanr10** [comment]
@nickdelta52 I'd like to wait on this a little bit, we're waiting mainly to figure out how we're going to analyze data, there's been talk of using mode instead of mean, possibly standard deviations. 

Additionally, we don't have the complete schema for the data yet. We'll revisit this once we have finalized the data collection
